image: java:latest

stages:
  - build

java 13 assemble:
  stage: build
  image: registry.gitlab.com/josm/docker-library/openjdk-13-josmplugin:latest
  script: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac /Fua\ Manager/src/fuamanager/FuaManager.java
  artifacts:
    paths:
      - build/
  allow_failure: true
